import type { Metadata } from "next";
import "./globals.css";
import HomeLayout from "@/component/Layout/App";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HomeLayout >
          {children}
        </HomeLayout>
      </body>
    </html>
  );
}
